### ISSUE TITLE
homey v2 not compatibel with 3.1.0

### ISSUE THREAD

**Issue by satbopper** [gruijter/com.gruijter.magister#17]
Under homey v2 magister 3.1.0 is not partly not compatibel 
if you try to config the app you can not see or select the student and furtherdebug logs refresh logs and delete logs is not working

**Comment by gruijter** [comment]
Is it only the app config page that doesnt work? Does the student device work as expected?

**Comment by satbopper** [comment]
no that i forgot for me if i say in a flow there is a new grade and say grade that flow will not be triggered,perhaps because it will not be in the log

**Comment by gruijter** [comment]
There is a problem with flows in homey v2. Should be solved in rc4.
