### ISSUE TITLE
New students are added twice

### ISSUE THREAD

**Issue by rhannink** [gruijter/com.gruijter.magister#21]
When I add a student (via parent login) in version 3.2.1. The new student appears twice in the app.
When I try to remove one of the duplicate students, I get an error that the device does not exist, but the double student is removed.

Under the app settings, the students information is also empty although I have added my two children.

[magisterlog.txt](https://github.com/gruijter/com.gruijter.magister/files/2767709/magisterlog.txt)

**Comment by gruijter** [comment]
Is this in homey v1 or v2?

**Comment by rhannink** [comment]
Homey V 2.0.0

**Comment by gruijter** [comment]
I didnt change anything in the pairing, only the login. So must be homey fw related. I will dig into this when I get my test homey. (But so many apps to test, and so little spare time😓)

**Comment by rhannink** [comment]
Check, no problem. With some workarounds everything seems to work.

Keep up the good work...
