### ISSUE TITLE
Icons are not showing in IOS app 

### ISSUE THREAD

**Issue by rhannink** [gruijter/com.gruijter.magister#22]
In the latest version off the IOS app, the icons:

"schoolStart": "./drivers/student/assets/schoolStart.svg",
"schoolEnd": "./drivers/student/assets/schoolEnd.svg",
"lastGrade": "./drivers/student/assets/lastGrade.svg",
"totalAverageGrade": "./drivers/student/assets/totalAverageGrade.svg"

Are not showing, I only see dashed squares as icons.

Homey 2.0.0 IOS app 2.0.1 (245) and Magister app 3.2.1
I have installed this version ci athom-cli

**Comment by gruijter** [comment]
I think custom capabilities have changed in homey v2. Will check. Thx 4 reporting!

**Comment by rhannink** [comment]
More apps are suffering from this, more info on custom capabilities in 2.0 see: [https://apps.developer.athom.com/tutorial-Drivers-Capabilities.html](url)

**Comment by rhannink** [comment]
Fixed it and made a pull request (3.2.2). Only icon line was missing in app.json.

**Comment by gruijter** [comment]
fixed with #23
