### ISSUE TITLE
Invalid username

### ISSUE THREAD

**Issue by glasn** [gruijter/com.gruijter.magister#24]
Ik heb sinds een paar dagen de Homey en Ik kan geen leerling toevoegen. Ik krijg steeds ‘invalid username’. Ik heb zowel als ouder en als leerling geprobeerd in te loggen. Beide geven dezelfde foutmeling. De inloggegevens zijn goed. Ik heb zojuist nog even geprobeerd. Bedankt voor de moeite.

**Comment by gruijter** [comment]
Is solved in #20 waiting for appstore release by athom.

**Comment by glasn** [comment]
Thx!

Verstuurd vanaf mijn iPhone
