### ISSUE TITLE
school and username&password or token are required

### ISSUE THREAD

**Issue by mkolsteeg** [gruijter/com.gruijter.magister#25]
Running v3.2.2 on Homey 2.0.0
Since the update to Homey 2.0.0 the app kept going to "Apparaat niet beschikbaar" with the additional remark "school and username&password or token are required" 

When I change someting to the login and change it back, it shortly seems to connect again only to fail after just a few seconds.

**Comment by gruijter** [comment]
Thx for reporting. I will be able to debug Homey V2 related issues once I receive my new test Homey. There are however also other apps that require my attention. So please be patient. Let me know if your situation changes  in the mean time.

**Comment by gruijter** [comment]
Should be fixed
