### ISSUE TITLE
invalid username

### ISSUE THREAD

**Issue by satbopper** [gruijter/com.gruijter.magister#27]
maybe the upcoming new school year is the cause but suddenly invalid username
i tried the parents login and same invalid username

**Comment by gruijter** [comment]
I just tested myself with 2 different schools and also get invalid username. Might be because it is still summer vacation. I will keep an eye on it.

**Comment by satbopper** [comment]
We both are right the new upcoming school year was the cause for the invalid user,so i close this issue
because my user is ok now
