### ISSUE TITLE
trigger for new grades seems not be working anymore

### ISSUE THREAD

**Issue by magtimmermans** [gruijter/com.gruijter.magister#3]
Hi,

Since the latest homey release the trigger for new grades seems not be working anymore. 
I think this has to do now because tokens are now typed. If app.json does not contain a type per token, it will be handled as strings. But on triggering these tokens must also contain strings. Because the app sets number values on these string typed tokens Homey will not trigger the flow card.
You can fix this issue by adding toString() on triggering per token value, or add type: 'number' per token in app.json.

please check if the value you pass as a token has the same type as the definition in app.json. If you didn't set the type (yet), Homey expects a string value.

**Comment by gruijter** [comment]
@magtimmermans Thanks for pointing this out! Trying to get my head around the new scheme with tokens and tags now. Will release a fix asap.

**Comment by gruijter** [comment]
@magtimmermans v1.0.1 should fix it. Could you check it please?

**Comment by magtimmermans** [comment]
Ok, I will check it. Of course I need to wait until a new grade is comming.. :)
