### ISSUE TITLE
Rooster

### ISSUE THREAD

**Issue by chrisboer** [gruijter/com.gruijter.magister#5]
Rooster wordt nog steeds opgenoemd door Homey terwijl de opties niet aangevinkt staan.

**Comment by gruijter** [comment]
Weird... Misschien moet je eens proberen om de app volledig te verwijderen en opnieuw te installeren. Check ook of je niet ergens een flow hebt gemaakt die het rooster opnoemt. Als in settings niets staat aangevinkt hoort hij ook niets te zeggen, tenzij je een flow hebt gemaakt die dat doet...

**Comment by gruijter** [comment]
@chrisboer heb je nog steeds het probleem?

**Comment by chrisboer** [comment]
Ik heb er geen problemen meer mee
