### ISSUE TITLE
Magister does not work with v1.2.0 rc8

### ISSUE THREAD

**Issue by chrisboer** [gruijter/com.gruijter.magister#6]
Error message 
<img width="1431" alt="magister" src="https://cloud.githubusercontent.com/assets/23163409/24247667/e57a6bd8-0fcc-11e7-8409-1264a64a4698.png">

Then deleted the student and completely reinstalled the app
Then when recreating the student I get this error.
<img width="1431" alt="magister1" src="https://cloud.githubusercontent.com/assets/23163409/24247700/046cda8a-0fcd-11e7-8bad-b6551a8dc913.png">

**Comment by gruijter** [comment]
Ok, thanx for reporting. I will investigate.

**Comment by chrisboer** [comment]
This is an App issue. The error message is just not displayed properly. I've tried to reproduce the issue, and the invalidly displayed error message was "Invalid API key". Please contact the app developer for further assistance.

**Comment by gruijter** [comment]
Indeed, an API issue with the magister.js library. I have made an issue with them. In the mean time not much I can do than wait for a fix in the API.....

**Comment by gruijter** [comment]
@chrisboer App update is just posted on GitHub :) The Magister.js builders already had a hotfix available :)
